### PR TITLE
refresh a gem a little

### PR DESCRIPTION
**Pull request by fazibear**
- remove jeweler
- Gemfile added
- fix dependencies
- update rspec
- nice and colorized output
- `-c` option works when downloading subtitles
- update README

### CODE REVIEW

**Comment by nofxx** [comment]
This is very cool, thank you.

**Comment by fazibear** [comment]
Can you bump version and release this ?

**Comment by nofxx** [comment]
Will do, removed ancient hpricot too, working with nokogiri.
Download is working fine for you?

**Comment by fazibear** [comment]
Yes, downloading works fine. Tested with nokogiri.

**Comment by nofxx** [comment]
All done, thanks again! Plus some rubocop and rspec 3.

**Pull request merged**
